### Import numpy library
 - Fundamental package for scientific computing with Python
 - NumPy library is the core library for scientif computing in Python. It provides High Multidimensional array object, and tools for working these array.

In [30]:
import numpy as np

Array of Vectors

In [31]:
array1 = np.array([1,2,3])
array2 = np.array([(1.5, 2, 3), (4,5, 6)], dtype = float)
array3 = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(array1.shape, array2.shape, array3.shape)
np.array([[1,2,3]]).shape

(3,) (2, 3) (2, 2, 3)


(1, 3)

Matrix Multiplication : Array Multiplication

In [32]:
array5 = np.random.randn(2,3)  # Generate an array of 2 rows and 3 columns by random function
array6 = np.random.rand(3,2)  # Generate an array of 3 rows and 2 columns by random function
np.matmul(array5, array6).shape # show the shape after multiplication
np.matmul(array5, array6)  # show the multiplied result

array([[0.83284132, 1.09491612],
       [0.83419817, 0.92931442]])

DOT Product between arrays

 \begin{align}
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i.
\end{align}    


In [33]:
value1 = np.random.randint(low=1, high =5, size = (1,3))
value2 = np.random.randint(low=1, high =5, size = (1,3))
print(value1)
print(value2)
np.dot(value1, value2.T) # T represent the transpose of a matrix

[[3 3 1]]
[[4 3 4]]


array([[25]])

### linalg *Norm*

In [34]:
np.linalg.norm(value1) # This show the normalization of value1 Array

4.358898943540674

### Normalize the vector to unit form

In [35]:
value1_normalized  = value1/np.linalg.norm(value1)
value1_normalized

array([[0.6882472 , 0.6882472 , 0.22941573]])

In [36]:
np.sum(np.power(value1_normalized,2))

0.9999999999999996

### cosine Similarity
\begin{align}
\frac{u \cdot v}
                   {{||u||}_2 {||v||}_2}
\end{align}

In [37]:
# install the library for cosine similarity
!pip install scipy   # pip commmand help to install required libraries

### cosine Dissimilarities
\begin{align}
1 - \frac{u \cdot v}
                   {{||u||}_2 {||v||}_2}
\end{align}

In [38]:
from scipy.spatial.distance import cdist
x = np.random.rand(1, 3)
y = np.random.rand(1,3)
x_normalized = x/np.linalg.norm(x)
y_normalized = y / np.linalg.norm(y)


In [39]:
np.sum(np.power(y_normalized,2))
np.sum(np.power(x_normalized,2))

0.9999999999999998

In [40]:
np.dot(x_normalized, y_normalized.T)

array([[0.67844111]])

In [41]:
cos_dissimilarity = cdist(x_normalized, y_normalized, metric =  'cosine')
cos_dissimilarity = 1 - cos_dissimilarity
cos_dissimilarity

array([[0.67844111]])

### Euclidean Dissimilarity
\begin{align}
   {||u-v||}_2 = (\sum{|u_i - v_i|^2})^{1/2}
\end{align}

In [42]:
cdist(x_normalized, y_normalized, metric = 'euclidean')

array([[0.80194625]])

In [43]:
np.sqrt(np.sum(np.power(np.abs(x_normalized - y_normalized), 2)))

0.8019462486081907

### Concatentate Vectors

In [44]:
x = np.random.randint(low = 1, high = 4, size = (1,3))
y = np.random.randint(low = 1, high = 4, size = (1,3))
x,y

(array([[2, 2, 2]]), array([[1, 1, 1]]))

In [47]:
np.concatenate((x,y), axis = 0)  # concatenate x and y via x-axis (x=0)

array([[2, 2, 2],
       [1, 1, 1]])

In [48]:
np.vstack((x,y))  # Vertical Stacking

array([[2, 2, 2],
       [1, 1, 1]])

In [50]:
np.hstack((x,y))  # Horizontal Stacking

array([[2, 2, 2, 1, 1, 1]])

### Element Wise Multiplication

In [51]:
x = np.random.randint(low = 1, high = 4, size = (2,2))
y = np.random.randint(low = 1, high = 4, size = (2,2))
print(x)
print(y)

[[3 1]
 [2 1]]
[[2 3]
 [2 1]]


In [52]:
np.multiply(x,y)

array([[6, 3],
       [4, 1]])

### Transpose of a Matrix

In [54]:
x = np.random.randint(low = 1, high = 4, size = (1,3))
print(x, x.T)
print(x.shape, x.T.shape)  # T represents Transpose

[[3 2 1]] [[3]
 [2]
 [1]]
(1, 3) (3, 1)


In [58]:
y = np.random.randint(low = 1, high = 4, size=(2,3))
print('shape = {} \n {} \n\n shape = = {} \n {}'.format(y.shape, y, y.T.shape, y.T))  # Represent the above same out using String formatting.

shape = (2, 3) 
 [[1 3 3]
 [1 2 2]] 

 shape = = (3, 2) 
 [[1 1]
 [3 2]
 [3 2]]


### Sequeeze
 - Reomve one dimensional entries from the shape of an array

In [63]:
arr = np.array([[[0], [1], [2]]])
print(arr, arr.shape)
print(np.squeeze(arr))
np.squeeze((arr).shape)
print(np.squeeze(arr, axis = 0), np.squeeze(arr, axis = 0).shape)
#print(np.squeeze(arr, axis = 1).shape)

[[[0]
  [1]
  [2]]] (1, 3, 1)
[0 1 2]
[[0]
 [1]
 [2]] (3, 1)


## REPEAT

In [64]:
print(np.repeat(3,4))
arr = np.array([[1,2], [3,4]])
print(x)
print(np.repeat(x,2))
print(np.repeat(x,3, axis = 1))
np.repeat(x,3 , axis = 0)

[3 3 3 3]
[[3 2 1]]
[3 3 2 2 1 1]
[[3 3 3 2 2 2 1 1 1]]


array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])