### Import torch library

In [1]:
import torch

In [3]:
device  = torch.device("cude:0" if torch.cuda.is_available() else "cpu")  # Check the availability of GPU 
device

device(type='cpu')

### Torch Vector
 - Return a tensor filled with ranom numbers from a uniform distribution on the interval (0,1).

In [6]:
tensor1 = torch.rand(2,3)  # create a tensor by 2 rows and 3 columns using randn function.
print(tensor1, tensor1.shape, type(tensor1))  

tensor([[0.0988, 0.7353, 0.7299],
        [0.1819, 0.2584, 0.0037]]) torch.Size([2, 3]) <class 'torch.Tensor'>


In [8]:
tensor1.to(device)  # set the tensor1 to available CPU or GPU

tensor([[0.0988, 0.7353, 0.7299],
        [0.1819, 0.2584, 0.0037]])

### Matrix Multiplication

In [11]:
import numpy as np # Imported NumPy Library
arr1 = np.random.randint(low = 1, high = 4, size= (2,3))
arr2 = np.random.randint(low = 1, high = 4, size= (2,3))
print(arr1)
print(arr2)

[[3 2 3]
 [1 3 2]]
[[3 2 1]
 [1 2 1]]


### Element Wise multiplicaition

In [12]:
arr1 = torch.randint(low = 1, high = 10, size = (2,3))
arr2 = torch.randint(low = 1, high = 10, size = (2,3))
print(arr1)
print(arr2)
torch.mul(arr1, arr2)

tensor([[6, 2, 4],
        [2, 1, 4]])
tensor([[6, 3, 1],
        [7, 5, 7]])


tensor([[36,  6,  4],
        [14,  5, 28]])

### Dot Product

In [14]:
arr1 = torch.randint(low = 1, high = 3, size = (1,3))
arr2 = torch.randint(low = 1, high = 3, size = (1,3))
print(arr1)
print(arr2)
torch.dot(arr1, arr2)

tensor([[1, 2, 2]])
tensor([[1, 2, 1]])


RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [18]:
print(torch.squeeze(arr1, dim = 0))
print(torch.squeeze(arr1, dim = 0))
torch.dot(torch.squeeze(arr1, dim = 0), torch.squeeze(arr2, dim = 0))

tensor([1, 2, 2])
tensor([1, 2, 2])


tensor(7)

### Normalize tensor

In [19]:
import torch.nn.functional as F
arr1 = torch.rand((1, 3))
arr1 = F.normalize(arr1)
arr1

tensor([[0.4650, 0.8531, 0.2366]])

In [20]:
torch.sqrt(torch.sum(torch.pow(arr1,2)))

tensor(1.0000)

### Cosine Similarity

In [22]:
value1 = torch.randn(10,100)
value2 = torch.rand(10,100)

cos_sim = torch.nn.CosineSimilarity(dim =1, eps = 1e-6)
result = cos_sim(value1, value2)
print(result)

tensor([-0.0351,  0.0107,  0.0621, -0.2307,  0.0858,  0.0230,  0.0492, -0.0092,
        -0.0213, -0.0520])


In [23]:
arr1 = torch.randn(1,128)
arr2 = torch.randn(1,128)
arr1_norm = F.normalize(arr1)
arr2_norm = F.normalize(arr2)
print(cos_sim(arr1, arr2),torch.dot(torch.squeeze(arr1_norm, dim = 0), torch.squeeze(arr2_norm, dim=0)))

tensor([0.0428]) tensor(0.0428)
