###  Pytorh and Numpy
- whether you can do in NumPy or you can do in Pytorch and much more in Both GPU and CPU

In [33]:
#import torch
import numpy as np
import torch

### torch.eye
 - torch.eye(number)   : number =3 , it create a three across identity matrix

In [4]:
number = 3
arr = torch.eye(number)
print(arr)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [5]:
arr = torch.eye(3,5)
print(arr)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


### torch.cat

In [6]:
x = torch.randint(low = 1, high = 3, size = (2,3))
y = torch.randint(low = 1, high = 3, size = (2,3))
print(x)
print(y)

tensor([[1, 2, 2],
        [1, 2, 1]])
tensor([[1, 2, 2],
        [1, 1, 1]])


In [8]:
torch.cat((x,y))  # here, default x= 0 

tensor([[1, 2, 2],
        [1, 2, 1],
        [1, 2, 2],
        [1, 1, 1]])

In [9]:
# Same as vStack
torch.vstack((x,y))

tensor([[1, 2, 2],
        [1, 2, 1],
        [1, 2, 2],
        [1, 1, 1]])

In [10]:
# Same as Hstack
torch.hstack((x,y))

tensor([[1, 2, 2, 1, 2, 2],
        [1, 2, 1, 1, 1, 1]])

In [13]:
x = x.T
print(x.shape, x.T.shape)

torch.Size([2, 3]) torch.Size([3, 2])


In [14]:
print(y)
torch.cat((x,y), axis = 1)  # axis =1 concatenate by columns wise

tensor([[1, 2, 2],
        [1, 1, 1]])


tensor([[1, 2, 2, 1, 2, 2],
        [1, 2, 1, 1, 1, 1]])

### torch unbind
 - Remove tensor dimension
 - Return a tuple of all slices along a given dimension

In [15]:
x = torch.randint(low = 1, high = 4, size = (3,2,4))
print(x)

tensor([[[3, 3, 3, 1],
         [3, 1, 2, 3]],

        [[2, 3, 1, 3],
         [1, 3, 2, 1]],

        [[2, 2, 2, 1],
         [2, 2, 1, 1]]])


In [17]:
f = torch.unbind(x, dim = 0)
print(len(f))
print(f[0], f[1], f[2])

3
tensor([[3, 3, 3, 1],
        [3, 1, 2, 3]]) tensor([[2, 3, 1, 3],
        [1, 3, 2, 1]]) tensor([[2, 2, 2, 1],
        [2, 2, 1, 1]])


In [19]:
f = torch.unbind(x, dim = 1)
print(len(f))
print(f[0], f[1])

2
tensor([[3, 3, 3, 1],
        [2, 3, 1, 3],
        [2, 2, 2, 1]]) tensor([[3, 1, 2, 3],
        [1, 3, 2, 1],
        [2, 2, 1, 1]])


### Euclidean distance in Pytorch

In [21]:
euc_distance = torch.nn.PairwiseDistance(p=2)
value1 = torch.randn(2,3)
value2 = torch.randn(2,3)
result  = euc_distance(value1, value2)
print(result)

tensor([1.8322, 0.8372])


### Search topn 
 - useful, which search for bulky products on top in products.
 -  Here, created three by four dimensional matrix

In [29]:
y = torch.randint(low = 1, high = 100, size = (3,4))
print(y)

tensor([[89, 57, 11, 71],
        [30, 39, 83, 14],
        [ 8,  5, 65, 95]])


In [30]:
torch.topk(y,3)

torch.return_types.topk(
values=tensor([[89, 71, 57],
        [83, 39, 30],
        [95, 65,  8]]),
indices=tensor([[0, 3, 1],
        [2, 1, 0],
        [3, 2, 0]]))

### Tensor Views
 - Pytorch allow a tensor to be view of an existing tensor. View tensor shares the same underlying tensor.
 - Suppororting view avoids explicit data copy, thus allow us to do fast and memory efficient and element wise operations.
 

In [31]:
arr = torch.randint(low = 1, high = 5, size = (1,4))
print(arr, arr.shape)

tensor([[4, 1, 1, 2]]) torch.Size([1, 4])


In [32]:
print(arr.view(4), arr.view(4).shape)

tensor([4, 1, 1, 2]) torch.Size([4])
