### Importing the basic libraries

In [2]:
# Importing the libraries CV2 
import cv2

In [3]:
# import the library for scientif matrix calculation
import numpy

### Reading and Writing Images
 - OpenCV provides the imread() and imwrite() functions that support various file
formats for still images.
 
 - No matter the format, each pixel has a value, but the difference is in how the pixel is
represented. For example, we can create a black square image from scratch by simply
creating a 2D NumPy array:

In [7]:
img = numpy.zeros((3,3), dtype = numpy.uint8) 
img

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

Each pixel is represented by a single 8-bit integer, which means that the values for
each pixel are in the 0-255 range.

Let's now convert this image into Blue-green-red (BGR) using cv2.cvtColor:

In [8]:
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

each pixel is now represented by a three-element array, with each
integer representing the B, G, and R channels, respectively.

You can check the structure of an image by inspecting the shape property, which
returns rows, columns, and the number of channels (if there is more than one).

In [10]:
img = numpy.zeros((3,3), dtype=numpy.uint8)
img

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [11]:
img.shape

(3, 3)

Images can be loaded from one file format and saved to another. For example, let's
convert an image from PNG to JPEG

In [13]:
image = cv2.imread('dog.jpg')
image

array([[[106, 171, 150],
        [106, 171, 150],
        [107, 172, 151],
        ...,
        [113, 176, 156],
        [113, 177, 155],
        [113, 177, 155]],

       [[106, 171, 150],
        [106, 171, 150],
        [107, 172, 151],
        ...,
        [113, 176, 156],
        [113, 177, 155],
        [113, 177, 155]],

       [[106, 171, 150],
        [106, 171, 150],
        [107, 172, 151],
        ...,
        [113, 176, 156],
        [113, 177, 155],
        [113, 177, 155]],

       ...,

       [[ 33, 120,  84],
        [ 69, 153, 118],
        [ 67, 144, 107],
        ...,
        [ 82, 146, 117],
        [ 79, 146, 117],
        [ 75, 145, 114]],

       [[ 35, 122,  86],
        [ 71, 153, 118],
        [ 85, 159, 123],
        ...,
        [ 82, 149, 118],
        [ 79, 149, 118],
        [ 74, 147, 115]],

       [[ 26, 113,  77],
        [ 35, 117,  82],
        [ 51, 128,  91],
        ...,
        [ 85, 152, 121],
        [ 82, 152, 121],
        [ 76, 149, 117]]

In [15]:
cv2.imwrite('Dog_Image_Format_Change.jpg', img)

True

By default, imread() returns an image in the BGR color format even if the file uses a
grayscale format. BGR represents the same color space as red-green-blue (RGB), but
the byte order is reversed.

Optionally, we may specify the mode of imread() to be one of the following
enumerators: